### PR TITLE
Major AUT execution refactor

### PR DESCRIPTION
**Pull request by jakubgs**
Because just can't keep looking at it. Here's list of changes:

* Removing `ATTACH_MODE` since as far as I can tell it's always `true`.
* Drop unnecessary killing of processes by port, we have the PID.
* Split `stop()` method into `_detach_context()` and `_kill_process()`.
* Use `psutil` methods like `kill()` and `wait()` instead of iterating processes for no reason.
* Drop use of recursion which is completely unnecessarily complex. Use loop.
* Remove checking of `returncode` right away after process starts, it's too soon.
* Lower `PROCESS_TIMEOUT_SEC` to 5 seconds to avoid needless delays.
* Send application logs to `aut.log` and server logs to `squish.log` files.
* Send all `pytest` logs to `pytest.log` file since `caplog` module suppresses them.
* Rename `APP_DIR` to `AUT_PATH`. The name APP_DIR suggests the path is a directory, but it's not.
* Drop retries from `launch()` method since they do not help and just add complexity.
* Refactor `init_testrail_api` to simplify without changing logic.
* Add `squish.ini` config to avoid needless calls to `squishserver` that just waste time.

Related to:
* https://github.com/status-im/desktop-qa-automation/issues/348
* https://github.com/status-im/desktop-qa-automation/issues/323

### CODE REVIEW

**Comment by jakubgs** [comment]
I'm wondering if we want to have separate `stderr` and `stdout` log files. We could combine them.

**Comment by jakubgs** [comment]
Holy shit it works:

image

**Comment by anastasiyaig** [comment]
it works! 

image

**Comment by anastasiyaig** [comment]
@jakubgs lets try on all tests we have

**Comment by jakubgs** [comment]
Some things to do in separate PRs, because I want to avoid growing this one endlessly:

- Add log level parameter for `pytest` logs in the `Jenkinsfile`.
- Rename all instances of `_logger` to `LOG` to match my other changes.
- MOAR logging in general, especially on `debug` level.

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
