### PR TITLE
test: re-importing seed phrase added to existing test

### PR DESCRIPTION
**Pull request by Valentina1133**
I added re-importing seed phrase and verifying keys already exist popup to existing test. 

CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1937/

Screenshot 2024-05-27 at 14 22 20

### CODE REVIEW

**Comment by Valentina1133** [comment]
tests are failing because I added object name but it's not merged to master yet

**Comment by anastasiyaig** [comment]
I think the object name was already merged?

**Comment by Valentina1133** [comment]
> I think the object name was already merged?

Yes, I merged it today

**Comment by anastasiyaig** [comment]
okay i restarted the tests and now they are passing. I also launched the test locally for last nightly and it works on my Linux

**Review by anastasiyaig — APPROVED** [review]

**Review by antdanchenko — APPROVED** [review]

**Pull request merged**
