### PR TITLE
ci: set short build name and better description

### PR DESCRIPTION
**Pull request by jakubgs**
Improvement upon:

* https://github.com/status-im/desktop-qa-automation/pull/214/files

### CODE REVIEW

**Comment by jakubgs** [comment]
Result for a manual build: https://ci.status.im/job/status-desktop/job/e2e/job/manual/661/

image

And in the build list:

image

**Comment by StateOf-Vlado** [comment]
> Result for a manual build: https://ci.status.im/job/status-desktop/job/e2e/job/manual/661/
> 
> image
> 
> And in the build list:
> 
> image
> 
> I still need to fix how we display nightly e2e runs. But that's a separate PR.

We don't need nightly if we start tests on master branch on each merge PR in the master

**Comment by jakubgs** [comment]
Why are you quoting the whole comment?

>We don't need nightly if we start tests on master branch on each merge PR in the master.

1. That's not the issue.
2. Why would we be doing that?

**Comment by StateOf-Vlado** [comment]
> > Result for a manual build: https://ci.status.im/job/status-desktop/job/e2e/job/manual/661/
> > image
> > And in the build list:
> > image
> > I still need to fix how we display nightly e2e runs. But that's a separate PR.
> 
> We don't need nightly if we start tests on master branch on each merge PR in the master

Wow, that's cool, 

> Result for a manual build: https://ci.status.im/job/status-desktop/job/e2e/job/manual/661/
> 
> image
> 
> And in the build list:
> 
> image
> 
> I still need to fix how we display nightly e2e runs. But that's a separate PR.

Looks cool, what do you think, if we have all the details in the build description, can we use just the build number as the name build how it was previously?  But developers may want to have a PR number in the name and in the description.

**Comment by StateOf-Vlado** [comment]
> Why are you quoting the whole comment?
> 
> > We don't need nightly if we start tests on master branch on each merge PR in the master.
> 
> 1. That's not the issue.
> 2. Why would we be doing that?
oh, I like it, we don't need to do that ))

**Comment by jakubgs** [comment]
Are you drunk?

**Comment by StateOf-Vlado** [comment]
> Are you drunk?

not yet, do you want to join?

**Review by StateOf-Vlado — APPROVED** [review]

**Pull request merged**
