### PR TITLE
1-1 chat, send reply, send emoji, edit, delete and cannot delete other member message

### PR DESCRIPTION
**Pull request by Valentina1133**
Test for 1-1 chat created

CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1675/allure/

https://ci.status.im/job/status-desktop/job/e2e/job/manual/1689/ - after changes for stabilisation
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1691/ - after changes for stabilisation
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1692/ - whole run after changes for stabilisation

### CODE REVIEW

**Review by anastasiyaig — COMMENTED** [review]
noticed 2 time.sleep usages but i guess they are necessary ?

**Comment by Valentina1133** [comment]
> noticed 2 time.sleep usages but i guess they are necessary ?

Tried to get rid of them but unfortunately didn't work

**Comment by anastasiyaig** [comment]
i changed the location of the test (moved to messages folder)
i also noticed that we refer to hardcoded text when asserting the messages, that has to be changed: first, i think we need to replace hardcoded sentence with string generator of certain length (adding special chars , numbers etc) and we need to store that string in variable

**Comment by anastasiyaig** [comment]
full run on today's master seem to be okay, but local launch of the new test is kinda flaky (it passes with rerun)

**Pull request merged**
