### PR TITLE
test: member role tests added

### PR DESCRIPTION
**Pull request by Valentina1133**
Test run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1214/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1248/
Test cases:
https://ethstatus.testrail.net/index.php?/cases/view/703269
https://ethstatus.testrail.net/index.php?/cases/view/703270
https://ethstatus.testrail.net/index.php?/cases/view/703271
https://ethstatus.testrail.net/index.php?/cases/view/703272
https://ethstatus.testrail.net/index.php?/cases/view/703273
https://ethstatus.testrail.net/index.php?/cases/view/703274

### CODE REVIEW

**Review by anastasiyaig — APPROVED** [review]

**Review by glitchminer — COMMENTED** [review]
Had some errors locally with test_communities_channel. Do we now have a minimum supported version?

image

**Comment by Valentina1133** [comment]
> Had some errors locally with test_communities_channel. Do we now have a minimum supported version?
> 
> image

That’s interesting🤨 I don’t know anything about needed versions. I use user data in this test maybe there is some conflict, don’t know

**Comment by anastasiyaig** [comment]
i ran it locally 1 by one and all together, it works @glitchminer could it be smth on your side? also, what do u mean under supported version?

Screenshot 2023-12-18 at 16 45 25

**Comment by anastasiyaig** [comment]
@Valentina1133 please resolve conflicts and i will merge

**Comment by Valentina1133** [comment]
> @Valentina1133 please resolve conflicts and i will merge

Conflicts resolved - [ ]

**Pull request merged**
