### PR TITLE
fix(aut): detach own context, not current one

### PR DESCRIPTION
**Pull request by jakubgs**
Seems wrong to me. My understanding is that context is specific to given AUT being run.

### CODE REVIEW

**Comment by jakubgs** [comment]
It appears all tests have failed with:
```
Exception: Current context is not the same as one being detached.
```
So that means that `self.ctx` is wrong, or `squish.currentApplicationContext()` is used correctly.

**Comment by jakubgs** [comment]
Also found an issue with use of `BUILD_NUMBER` to add as port offset instead of `EXECUTOR_NUMBER`.

**Comment by anastasiyaig** [comment]
I noticed the app context error today:

```
TypeError: Cannot switch to invalid application context
```

I don't really understand what is going on here, why `attach to app` step is trying to close application and then fails with the error above but is marked as green

Screenshot 2024-01-19 at 09 02 15

**Comment by anastasiyaig** [comment]
@jakubgs are you up to continue working on this (just not sure what is left :D)

**Comment by jakubgs** [comment]
I don't have the time, nor do I even remember what this was for.

**Pull request closed without merging**
