### PR TITLE
chore: replace mouse type in click mouse method

### PR DESCRIPTION
**Pull request by StateOf-Vlado**
Fix issue: 
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/87/allure/#suites/804b25da7c0d1c4c7f8a050c6a89e043/e7f7d2c3371a670f/
Test run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1059/

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@StateOf-Vlado is it fixing communties? Some context would be nice

**Comment by Valentina1133** [comment]
Maybe it makes sense to run all tests for this branch? Because this change is not only for communities, but for the method which we use in all tests

**Comment by anastasiyaig** [comment]
@Valentina1133 we run tests for pr, all tests. Expand the checklist of this pr and there is a check failed.  can see the results

**Comment by anastasiyaig** [comment]
https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-327/1/display/redirect

**Comment by StateOf-Vlado** [comment]
> @StateOf-Vlado is it fixing communties? Some context would be nice

Link to the issue added in description

**Comment by anastasiyaig** [comment]
Okay, i ran the same test in 2 branches:

1. chore/onboarding_tests which is a master branch with create community test enabled . Test is passing just fine now
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1078/parameters/

Screenshot 2023-11-22 at 15 17 51


2. this branch - test is getting stuck 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1078/parameters/

Screenshot 2023-11-22 at 15 18 17

3. i even created my own branch with the changes present in this branch (copypasted them), test still stuck
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1077/

Screenshot 2023-11-22 at 15 20 35

What i will do - i will enable community creation tests without having this change. @StateOf-Vlado please take a look when u have time

**Comment by anastasiyaig** [comment]
I ran all tests in master and it hang communities right away https://ci.status.im/job/status-desktop/job/e2e/job/manual/1079/console

But the fact is , if i launch community test as the only test to run - it is green
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1078/parameters/

So with this said, communities are not working yet neither for this branch, nor for master

**Pull request closed without merging**
