### PR TITLE
chore: squish waitFor method was customized

### PR DESCRIPTION
**Pull request by StateOf-Vlado**
#262
https://ci.status.im/job/status-desktop/job/e2e/job/manual/805/

image

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@StateOf-Vlado please, attach the screenshots of successful run. Everyone does that already.

**Comment by StateOf-Vlado** [comment]
> @StateOf-Vlado please, attach the screenshots of successful run. Everyone does that already.

Done

**Review by Valentina1133 — APPROVED** [review]

**Comment by Valentina1133** [comment]
> > @StateOf-Vlado please, attach the screenshots of successful run. Everyone does that already.
> 
> Done

You did this for keycard test, right? I think we should run it on keycard test then to make sure that it helped

**Comment by anastasiyaig** [comment]
also, i am seeing GH check failed (which means tests failed)

**Review by glitchminer — APPROVED** [review]

**Comment by StateOf-Vlado** [comment]
> also, i am seeing GH check failed (which means tests failed)

Sometimes, we see what we want to see.
But if you go to the details, you find the reason:
```
Unable to find a project for artifact copy: 

This may be due to incorrect project name or permission settings; see help for project name in job configuration.
```
So, that doesn't mean that tests failed.

**Pull request merged**
